env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  no-const-assign:
    - error
  no-var:
    - error
  no-new-object:
    - error
  object-shorthand:
    - error
