env:
  browser: true
  node: true
  commonjs: true
  jasmine: true
  es6: true
extends: 'eslint:recommended'
rules:
  no-eval:
    - error
  no-console:
    - off
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  no-const-assign:
    - error
  no-var:
    - error
  no-new-object:
    - error
  object-shorthand:
    - error
  max-len:
    - error
    - 80
  prefer-rest-params:
    - error
  no-new-func:
    - error
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
  space-before-blocks:
    - error
  no-param-reassign:
    - error
    - props: true
  prefer-spread:
    - error
  prefer-arrow-callback:
    - error
  arrow-spacing:
    - error
  arrow-parens:
    - error
  arrow-body-style:
    - error
    - as-needed
  eqeqeq:
    - error
  no-nested-ternary:
    - error
  no-unneeded-ternary:
    - error
  spaced-comment:
    - error
