env:
  browser: true
  node: true
  commonjs: true
  jasmine: true
  es6: true
parserOptions:
    ecmaVersion: 8
    ecmaFeatures:
        impliedStrict: true
        experimentalObjectRestSpread: true
plugins:
  - 'prettier'
extends: 'eslint:recommended'
rules:
  prettier/prettier:
    - error
    - arrowParens: always
      singleQuote: true
      semi: false
  no-eval:
    - error
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  no-const-assign:
    - error
  no-var:
    - error
  no-new-object:
    - error
  object-shorthand:
    - error
  prefer-rest-params:
    - error
  no-new-func:
    - error
  no-param-reassign:
    - error
    - props: true
  prefer-spread:
    - error
  prefer-arrow-callback:
    - error
  eqeqeq:
    - error
  no-nested-ternary:
    - error
  no-unneeded-ternary:
    - error
  spaced-comment:
    - error
